// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HistoricalDataService.proto

package smart.air.pollution.historicaldata;

public interface GetHistoricalDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetHistoricalDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 TimeStamp = 1;</code>
   */
  long getTimeStamp();

  /**
   * <code>int32 AQI = 2;</code>
   */
  int getAQI();

  /**
   * <code>.Pollutant pollutants = 3;</code>
   */
  boolean hasPollutants();
  /**
   * <code>.Pollutant pollutants = 3;</code>
   */
  smart.air.pollution.historicaldata.Pollutant getPollutants();
  /**
   * <code>.Pollutant pollutants = 3;</code>
   */
  smart.air.pollution.historicaldata.PollutantOrBuilder getPollutantsOrBuilder();
}
